### ISSUE TITLE
Publish to Logseq marketplace

### ISSUE THREAD

**Issue by YU000jp** [YU000jp/logseq-plugin-legacy-date-format#1]
- [x] Need to finalize this plugin title before submitting
- [x]  Resolve other issues
- [x] Edit README.md for publish version
- [x] Check at release file (.zip)
- [x] icon.png
- [x] manifest.json
- [x] Pull request to Logseq marketplace https://github.com/logseq/marketplace/pull/
- [ ] Check after publish
- [x] Edit README.md for after publish
- [x] Discord
- [x] https://github.com/YU000jp

**Comment by candideu** [comment]
Thank you for making this plugin! It's much needed. 😃

**Comment by YU000jp** [comment]
This plugin replace inactive links with journal attributes.They function as both links and references within. They are necessary.
While ideally, it should be integrated as a re-index feature within Logseq implementation itself, I personally lack sufficient knowledge of ClojureScript programming. As an alternative approach, I have prepared it as a plugin in TypeScript.
